# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_polars+pytorch.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/01_polars+pytorch.ipynb 3
# Re-export from core for backward compatibility
from asterisms_py.core import (
    SearchConfig, NAKED_EYE, BINOCULAR, TELESCOPIC,
    ScoreItem, Points,
    convert_to_cartesian, calculate_distances,
    distance_from_magnitude, distance_from_magnitude_tensor,
    tetrahedron_score, square_score,
    measure_squareness_old, measure_squareness,
    radecmag_to_cartesian, radecmag_to_angular,
    mass_score_triangle_torch, transform_radecmag_from_numpy,
    global_normalize_tensor, radec_normalize_tensor,
    mag_score, score_triangle,
    stars_for_point_and_radius, stars_for_center_and_radius,
    get_grid_points, get_grid_point_by_idx, get_region, get_center,
    ra_to_hms, resultdf,
    load_catalog_to_gpu, reset_gpu_catalog, filter_stars_on_gpu,
    vectorized_filter_batch, process,
    process_all_regions, _score_region, _detect_gpu_backend,
    triangle_extent_deg, triangle_extent_deg_batch,
    chain_extent_deg, score_collinear_region, process_collinear_regions,
)
